### ISSUE TITLE
How to call this function user_login

### ISSUE THREAD

**Issue by digicharan** [danielneis/moodle-auth_ws#1]
Hello,

Thank you for your module. I have installed your plugin in moodle successfully.

Now, I want to login to my moodle website by using an external api from my page http://localhost/login.php. Can you please give me sample code on how to call this API. 

I was a new bee to Moodle.

Thanks in advance for your help

Charan...

**Comment by danielneis** [comment]
do you have a working soap webservice on this localhost ? or do you want to login into moodle from a form on this localhost/index.php ? if the later is what you want, you just need to point your form to your moodle install /login/index.php ....

**Comment by digicharan** [comment]
Hello Daniel,

Thank you for your reply.

I have a working REST web service on my localhost. To which URL, I need to post my data for login? 

Ex: http://www.mywebsite.com/webservice/rest/server.php'. '?wstoken=' . $token . '&wsfunction='.$functionname; (Used to post data to Moodle)

**Comment by danielneis** [comment]
this plugin does not work with rest yet, but if you are willing to make the changes, you just need to change the function at: https://github.com/danielneis/moodle-auth_ws/blob/master/auth.php#L92

if you would like to authenticate against another moodle, I would suggest using the external database authentication.
