### ISSUE TITLE
How to create a new user's profile?

### ISSUE THREAD

**Issue by lvddrint** [danielneis/moodle-auth_ws#2]
Hi,

Thanks for your module.  I have a question regarding to creating user's profile after successfully login.
For auth.php, after user_login($username, $password) return true.  Moodle directs users to /users/edit.php which shows blank. I can get user's profile from external webservice but not sure how to pass these information to the edit.php page.

Please advise.

Thanks in advance.
Linh

**Comment by danielneis** [comment]
You must change the "is_synchronised_with_external" function at
https://github.com/danielneis/moodle-auth_ws/blob/master/auth.php#L134 to return true.
Then you must implement the "get_userinfo" function at https://github.com/danielneis/moodle-auth_ws/blob/master/auth.php#L88 to return the information for the user. See the fields on user table that Moodle may use to check if user is confirmed/complete.

I found that looking at moodle/login/index.php , that calls for authenticate_user.
