### ISSUE TITLE
Problema para entender o plugin

### ISSUE THREAD

**Issue by DeeSouza** [danielneis/moodle-auth_ws#3]
Daniel.

Qual a diferença da autenticação feita pelo seu plugin e fazer a autenticação pelo endpoint /login/token.php que o próprio Moodle tem?

Eu vi que no seu plugin os usuários precisam estar com o tipo de autenticação marcada como WebService. Mas e se for um Moodle que já existe, com muitos usuários?

PS: Já saiu o Moodle Mobile com a interface atualizada, Ionic 3?

**Comment by danielneis** [comment]
Olá,

este plugin serve para quando a autenticação precisa ser feita contra um webservice externo. É como se fosse a autenticação em LDAP ou Base de dados externa, mas num webservice soap.

sobre o moodle mobile novo, ainda não saiu. acompanhar em https://github.com/moodlehq/moodlemobile2/tree/v3.5.0
