### ISSUE TITLE
SOAP-ERROR: Parsing WSDL

### ISSUE THREAD

**Issue by DRoma82** [danielneis/moodle-auth_ws#4]
When I try to use your plugin, I'm getting the following error:

xception - SOAP-ERROR: Parsing WSDL: Couldn't load from '?wsdl' : failed to load external entity "?wsdl"

Stack trace:
line 98 of /auth/ws/auth.php: SoapFault thrown
line 98 of /auth/ws/auth.php: call to SoapClient->SoapClient()
line 70 of /auth/ws/auth.php: call to auth_plugin_ws->call_ws()
line 4305 of /lib/moodlelib.php: call to auth_plugin_ws->user_login()
line 140 of /login/index.php: call to authenticate_user_login()

Output buffer: <br /> <b>Notice</b>: Undefined property: stdClass::$auth_serverurl in <b>/opt/bitnami/apps/moodle/htdocs/auth/ws/auth.php</b> on line <b>70</b><br />

I'm trying to make it connect to a .NET svc Web Service. Is it compatible?

Thanks!

**Comment by danielneis** [comment]
Hello.
It should be compatible.
It seems it was using the wrong config key. I published a new commit that should fix that.
